while True:
    print("\nEscolha uma opção")
    print("1: converter um arquivo")
    print("2: converter um texto")
    option = int(input("Opção: "))
    if option == 1:
        file = open(input, 'r')
        linhas = file.readlines()[1:]
        linhas = linhas.upper()
        linhas = linhas.replace('A','.- ')
        linhas = linhas.replace('B','-... ')
        linhas = linhas.replace('C','-.-. ')
        linhas = linhas.replace('D','-.. ')
        linhas = linhas.replace('E','. ')
        linhas = linhas.replace('F','..-. ')
        linhas = linhas.replace('G','--. ')
        linhas = linhas.replace('H','.... ')
        linhas = linhas.replace('I','.. ')
        linhas = linhas.replace('J','.--- ')
        linhas = linhas.replace('K','-.- ')
        linhas = linhas.replace('L','.-.. ')
        linhas = linhas.replace('M','-- ')
        linhas = linhas.replace('N','-. ')
        linhas = linhas.replace('O','--- ')
        linhas = linhas.replace('P','.--. ')
        linhas = linhas.replace('Q','--.- ')
        linhas = linhas.replace('R','.-. ')
        linhas = linhas.replace('S','... ')
        linhas = linhas.replace('T','- ')
        linhas = linhas.replace('U','..- ')
        linhas = linhas.replace('V','...- ')
        linhas = linhas.replace('W','.-- ')
        linhas = linhas.replace('X','-..- ')
        linhas = linhas.replace('Y','-.-- ')
        linhas = linhas.replace('Z','--.. ')
        file = open('texto_morse.txt', 'a')
        file.write(linhas)
        file.close
    if option == 2:
        texto = input('adicione um texto para converter em código morse: ').upper()
        texto = texto.replace('A','.- ')
        texto = texto.replace('B','-... ')
        texto = texto.replace('C','-.-. ')
        texto = texto.replace('D','-.. ')
        texto = texto.replace('E','. ')
        texto = texto.replace('F','..-. ')
        texto = texto.replace('G','--. ')
        texto = texto.replace('H','.... ')
        texto = texto.replace('I','.. ')
        texto = texto.replace('J','.--- ')
        texto = texto.replace('K','-.- ')
        texto = texto.replace('L','.-.. ')
        texto = texto.replace('M','-- ')
        texto = texto.replace('N','-. ')
        texto = texto.replace('O','--- ')
        texto = texto.replace('P','.--. ')
        texto = texto.replace('Q','--.- ')
        texto = texto.replace('R','.-. ')
        texto = texto.replace('S','... ')
        texto = texto.replace('T','- ')
        texto = texto.replace('U','..- ')
        texto = texto.replace('V','...- ')
        texto = texto.replace('W','.-- ')
        texto = texto.replace('X','-..- ')
        texto = texto.replace('Y','-.-- ')
        texto = texto.replace('Z','--.. ')
        file = open('texto_morse.txt', 'a')
        file.write(texto)
        file.close
        
