print('doações para compra de cestas básicas')
print('informe a quantidade de itens para doação')
arroz = int(input('quantidade de arroz que deseja doar:'))
feijão = int(input('quantidade de feijão que deseja doar:'))
óleo = int(input('quantidade de óleo que deseja doar:'))
sal = int(input('quantidade de sal que deseja doar:'))
açúcar = int(input('quantidade de açúcar que deseja doar:'))
café = int(input('quantidade de café que deseja doar:'))
molho_tomate = int(input('quantidade de molho de tomate que deseja doar:'))
macarrão = int(input('quantidade de macarrão que deseja doar:'))
farinha_trigo = int(input('quantidade de farinha de trigo que deseja doar:'))
pão = int(input('quantidade de pão que deseja doar:'))
manteiga = int(input('quantidade de manteiga que deseja doar:'))
banana = int(input('quantidade de banana que deseja doar:'))
leite = int(input('quantidade de leite que deseja doar:'))
sabonete = int(input('quantidade de sabonete que deseja doar:'))
creme_dental = int(input('quantidade de creme dental que deseja doar:'))
escova_dente = int(input('quantidade de escovas de dente que deseja doar:'))
desodorante = int(input('quantidade de desodorantes que deseja doar:'))
absorvente = int(input('quantidade de absorventes que deseja doar:'))
shampoo = int(input('quantidade de shampoos que deseja doar:'))
papel_higiénico = int(input('quantidade de papéis higiénicos que deseja doar:'))
detergente = int(input('quantidade de detergente que deseja doar:'))
sabão_barra = int(input('quantidade de sabão em barra que deseja doar:'))
sabão_pó = int(input('quantidade de sabão em pó que deseja doar:'))
amaciante = int(input('quantidade de amaciante que deseja doar:'))
água_sanitaria = int(input('quantidade de agua sanitaria que deseja doar:'))
multiuso = int(input('quantidade de multiuso que deseja doar:'))
esponja_aço = int(input('quantidade de esponjas de aço que deseja doar:'))
valor =int(input('informe o valor que deseja doar'))
cesta = int(arroz * 5.50) + int(feijão * 6.00) + int(óleo * 7.50) + int(sal * 1.99) + int(açúcar * 4)\
     + int(café * 6.7) + int(molho_tomate * 1.2) + int(macarrão * 2.8) + int(farinha_trigo * 5.3) + int(pão * 5)\
     + int(manteiga * 3) + int(banana * 2) + int(leite * 3.5) + int(sabonete * 0.8) + int(creme_dental * 1)\
     + int(escova_dente * 0.8) + int(desodorante * 5.40) + int(absorvente * 1.9) + int(shampoo * 5)\
     + int(papel_higiénico * 10) + int(detergente * 0.5) + int(sabão_barra * 0.5) + int(sabão_pó * 5)\
     + int(amaciante * 4.5) + int(água_sanitaria * 1.99) + int(multiuso * 2.90) + int(esponja_aço * 0.3)   
print('o custo de cada cesta é: R$', cesta)
quantidade = int(valor // cesta)
print('com o valor doado podem ser compradas', quantidade , 'de cestas básicas')
